---
title: "OSB Simulation Model"
author: "Cassandra Doll"
date: "2/24/2020"
output: word_document
---

# Loading Required R Packages
```{r}
library(ggplot2)
library(reshape2)
library(magrittr)
library(ggpubr)
```

# Function
```{r}
OSBPop <- function(N0,Years,Simulations,k,kSD,s3,s3SD,h,hSD,f,fSD,g,gSD,e,eSD){

# Matrices
RndkSimulations = matrix(0,Simulations,Years)
Rnds3Simulations = matrix(0,Simulations,Years)
RndhSimulations = matrix(0,Simulations,Years)
RndfSimulations = matrix(0,Simulations,Years)
RndgSimulations = matrix(0,Simulations,Years)
RndeSimulations = matrix(0,Simulations,Years)
PopYears = matrix(0,Simulations,Years+1)
PopYears[,1] = N0

# Loops
## k
for (t in 1:Simulations){
  RndkSimulations[t,1:Years] = rnorm(Years, mean = k, sd = kSD)}
## s3
for (t in 1:Simulations){
  Rnds3Simulations[t,1:Years] = rnorm(Years, mean = s3, sd = s3SD)}
## h
for (t in 1:Simulations){
  RndhSimulations[t,1:Years] = rnorm(Years, mean = h, sd = hSD)}
## f
for (t in 1:Simulations){
  RndfSimulations[t,1:Years] = rnorm(Years, mean = f,sd = fSD)}
## g
for (t in 1:Simulations){
  RndgSimulations[t,1:Years] = rnorm(Years, mean = g, sd = gSD)}
## e
for (t in 1:Simulations){
  RndeSimulations[t,1:Years] = rnorm(Years, mean = e, sd = eSD)}

# Output
for(t in 1:Simulations){                                                           
for (y in 1:Years){
  PopYears[t,y+1] = 
    ifelse(PopYears[t,y]*RndkSimulations[t,y]*Rnds3Simulations[t,y]*RndhSimulations[t,y]*RndfSimulations[t,y]*RndgSimulations[t,y]*exp(RndeSimulations[t,y])>=1,
  round(PopYears[t,y]*RndkSimulations[t,y]*Rnds3Simulations[t,y]*RndhSimulations[t,y]*RndfSimulations[t,y]*RndgSimulations[t,y]*exp(RndeSimulations[t,y])),0)}}
return(PopYears)}
```

# Environmental Stochasticity
```{r}
# Annual census of OSB at Mt. Hebo
Year <- seq(1990,2002)
N <- c(1100,2888,2628,1041,2200,3413,2507,2664,2743,4983,2111,1402,2272)
Hebo <- data.frame(cbind(Year,N))

# e and eSD
r <- log(Hebo$N[-1]/Hebo$N[-length(Hebo$N)]) 
GeoMean <- mean(r)
e <- exp(GeoMean)
eSD <- sd(r)
```

# Parameter Estimates
```{r}
# N0, Years, and Simulations
N0 <- 100
Years <- 15
Simulations <- 50

# k and kSD
s1 <- 0.56
s2 <- 0.20
s4 <- 0.60
k <- s1*s2*s4
kSD <- 0

# s3 and s3SD
s3 <- 0.15
s3SD <- 0

# h and hSD
h <- 1
hSD <- 0

# f and fSD
f <- 82
fSD <- 0

# g and gSD
g <- 1
gSD <- 0

# e and eSD
e <- exp(GeoMean)
eSD <- sd(r)

# Run
PopYears <- OSBPop(N0,Years,Simulations,k,kSD,s3,s3SD,h,hSD,f,fSD,g,gSD,e,eSD)
```

# Extracting Population Sizes and Growth Rates
```{r}
# Sizes
PopSize <- PopYears
PopSize <- melt(PopSize)
colnames(PopSize) <- c('Simulation','Year','Size')
PopSize <- as.data.frame(PopSize)
PopSize$Simulation <- as.factor(PopSize$Simulation)
# Average sizes
AvgPop <- function(PopYears,Years){
Avg1 <- colMeans(PopYears)
AvgSimulation <- as.data.frame(Avg1)
AvgSimulation$Year <- c(0:Years)
return(AvgSimulation)}
AvgPopSize <- AvgPop(PopYears,Years)
AvgPopSize <- AvgPopSize[,c(2,1)]

# Rates
PopRates <- function(PopYears,Years){
Rate1 <- PopYears[,2:(Years+1)]/PopYears[,1:(Years)]
Rate2 <- melt(Rate1)
colnames(Rate2) <- c("Simulation","Year","Lambda")
return(Rate2)}
# Average rates
AvgRates <- function(PopYears,Years){
Rate1 <- PopYears[,2:(Years+1)]/PopYears[,1:(Years)]
GeoMean1 <- apply(Rate1, 2, function(x) (prod(x[x!=0]))^(1/sum(x!=0)))
AvgSimulation = as.data.frame(GeoMean1)
AvgSimulation$Year <- c(1:Years)
return(AvgSimulation)}
AvgLam <- AvgRates(PopYears,Years)
AvgLam <- AvgLam[,c(2,1)]
Rates <- PopRates(PopYears,Years)
Rates$Simulation <- as.factor(Rates$Simulation)
```

# Plotting Population Sizes and Growth Rates
```{r, fig.height = 6, fig.width = 14}
# Sizes
PopPlot <- ggplot() + geom_line(data = PopSize, aes(Year, Size, color = Simulation)) + scale_color_grey() + theme(legend.position = "none") + xlim(0,15) + ylim(0,1000000000)
PopPlot <- PopPlot + geom_line(data = AvgPopSize, aes(x = Year, y = Avg1), inherit.aes = FALSE, color = "red")

# Rates
LambdaPlot <- ggplot(data = Rates, aes(x = Year, y = Lambda, color = Simulation)) + geom_line() + scale_color_grey() + theme(legend.position = "none") + xlim(0,15)
LambdaPlot <- LambdaPlot + geom_line(data = AvgLam, aes(x = Year, y = GeoMean1), inherit.aes = FALSE, color = "red")

# Plots
ggarrange(PopPlot, LambdaPlot, 
          labels = c("A", "B"),
          ncol = 2, nrow = 1)
```

# Probability of Surviving Populations
## Function
```{r}
OSBPopProb <- function(N0,Years,Simulations,k,kSD,s3,s3SD,h,hSD,f,fSD,g,gSD,e,eSD){
# Matrices
RndkSimulations = matrix(0,Simulations,Years)
Rnds3Simulations = matrix(0,Simulations,Years)
RndhSimulations = matrix(0,Simulations,Years)
RndfSimulations = matrix(0,Simulations,Years)
RndgSimulations = matrix(0,Simulations,Years)
RndeSimulations = matrix(0,Simulations,Years)
PopYears = matrix(0,Simulations,Years+1)
PopYears[,1] = N0

# Loops
## k
for (t in 1:Simulations){
  RndkSimulations[t,1:Years] = rnorm(Years, mean = k, sd = kSD)}
## s3
for (t in 1:Simulations){
  Rnds3Simulations[t,1:Years] = rnorm(Years, mean = s3, sd = s3SD)}
## h
for (t in 1:Simulations){
  RndhSimulations[t,1:Years] = rnorm(Years, mean = h, sd = hSD)}
## f
for (t in 1:Simulations){
  RndfSimulations[t,1:Years] = rnorm(Years, mean = f,sd = fSD)}
## g
for (t in 1:Simulations){
  RndgSimulations[t,1:Years] = rnorm(Years, mean = g, sd = gSD)}
## e
for (t in 1:Simulations){
  RndeSimulations[t,1:Years] = rnorm(Years, mean = e, sd = eSD)}

# Output
for(t in 1:Simulations){                                                           
for (y in 1:Years){
  PopYears[t,y+1] = 
    ifelse(PopYears[t,y]*RndkSimulations[t,y]*Rnds3Simulations[t,y]*RndhSimulations[t,y]*RndfSimulations[t,y]*RndgSimulations[t,y]*exp(RndeSimulations[t,y])>=1,
  round(PopYears[t,y]*RndkSimulations[t,y]*Rnds3Simulations[t,y]*RndhSimulations[t,y]*RndfSimulations[t,y]*RndgSimulations[t,y]*exp(RndeSimulations[t,y])),0)}}
Count = array(1,Simulations)                 
  PopSurvive = sum(Count[PopYears[,Years+1]>0])
  ProbSurvive = PopSurvive/Simulations
  ProbSurvive
}
```
