---
title: "2019 A. B. James - Fig. S1"
author: "Cassandra F. Doll, Sarah J. Converse, Collin B. Edwards, and Cheryl B. Schultz"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    code_floading: hide
---

# Setup
## Loading Required R Packages

```{r, echo = T, results = 'hide', message = F, warning = F}
library(ggplot2)
library(here) # Organization
```

# Figure
## Adult Mass

```{r}
b.d <- read.csv(here("Data","2019 A. B. James.csv"))
b.d$Treat_ID <- factor(b.d$Treat_ID,levels = c("NC","C"))

levels(b.d$Treat_ID)[levels(b.d$Treat_ID)=="NC"] <- "No Competition"
levels(b.d$Treat_ID)[levels(b.d$Treat_ID)=="C"] <- "Competition"

Fig_S1 <- ggplot(b.d, aes(Treat_ID, A_Mass, fill = Treat_ID)) + geom_boxplot(width = 0.4)

Fig_S1 <- Fig_S1 + scale_fill_manual(breaks = c("No Competition","Competition"), values = c("white", "white")) + theme(legend.position = "none", axis.text.x = element_text(size = 8.5), axis.text.y = element_text(size = 8.5), title = element_text(size = 8.5), panel.background = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(color = "black"), axis.text = element_text(color = "black"), axis.ticks = element_line(color = "black")) + xlab("") + ylab('Adult Mass (g)') + guides(fill = FALSE)
Fig_S1 <- Fig_S1 + scale_y_continuous(
  labels = scales::number_format(accuracy = .01), limits = c(0.1,0.4))
print(Fig_S1)

ggsave(
  here("Figures", "Fig. S1.jpg"),
  Fig_S1,
  width = 174,
  height = 100,
  units = c("mm"),
  dpi = 600
)
```